sudo: required

env:
  - VERSION=latest
  - VERSION=1.3.1 URL=https://mirrors.ocf.berkeley.edu/apache/hbase/1.3.1/hbase-1.3.1-bin.tar.gz
  - VERSION=1.2.5 URL=https://archive.apache.org/dist/hbase/1.2.5/hbase-1.2.5-bin.tar.gz 
  - VERSION=1.2.4 URL=https://archive.apache.org/dist/hbase/1.2.4/hbase-1.2.4-bin.tar.gz 

services:
   - docker

script:
   - make build


before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: make deploy

